WINDOW_GIVEN      : 5040   # 1 week 
BATCH_SIZE        : 32
HIDDEN_DIM_LSTM   : 1024
NUM_LAYERS        : 1
EPOCHS            : 3
LEARNING_RATE     : 1.0e-3
DEVICE            : "cuda"
DROPOUT           : 0.2

train_data:
  train_A_path: "../data/train/TRAIN_A.csv"
  train_B_path: "../data/train/TRAIN_B.csv"

test_data:
  test_C_path: "../data/test/C"
  test_D_path: "../data/test/D"

submission_template:
  submission_template_path: "../data/submission/sample_submission.csv"

output_path:
  output_dir: "../data/submission"
  output_file_name_format: "{CURRENT_TIME}_bs{BATCH_SIZE}_epochs{EPOCHS}_lr{LEARNING_RATE}.csv"